### ISSUE TITLE
Error Handling.

### ISSUE THREAD

**Issue by pigeon-nation** [darek-margas/iotawatt-2-chargehq#2]
In relation to my pull request (API request/post error handling):

This code is being submitted in a response to the request for help by {info-removed}. I have added error handling to the requests section, and it can detect timeouts, as well as multiple other errors. The code is available in the PRs.

The code that I submitted catches all errors, on both the GET and POST requests. It looks for common errors, like timeout, but also prints any other errors to the console in detail (through force re-raising). If there is an error, the code will always exit to the status code 1, making the returning predictable, unless an error occurs elsewhere.

Hopefully this code is useful to somebody, 
Thanks, Pigeon Nation.

**Comment by darek-margas** [comment]
Fixed recently
